SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS TB_BOARD_ANSWER;
DROP TABLE IF EXISTS TB_BOARD_COMMENT;
DROP TABLE IF EXISTS TB_BOARD;
DROP TABLE IF EXISTS TB_FILE_INFO;




/* Create Tables */

CREATE TABLE TB_BOARD
(
	-- 게시글 ID
	BOARD_ID int NOT NULL AUTO_INCREMENT COMMENT '게시글 ID',
	BOARD_CODE varchar(10) NOT NULL,
	TITLE varchar(400) NOT NULL,
	CONTENTS text,
	VIEW_CNT int DEFAULT 0,
	-- Y/N
	ANSER_YN char(1) DEFAULT 'N' COMMENT 'Y/N',
	-- Y/N
	DEL_YN char(1) COMMENT 'Y/N',
	IN_USER varchar(20) NOT NULL,
	IN_DATE datetime NOT NULL,
	UP_USER varchar(20),
	UP_DATE datetime,
	PRIMARY KEY (BOARD_ID)
);


CREATE TABLE TB_BOARD_ANSWER
(
	BA_ID int NOT NULL,
	-- 게시글 ID
	BOARD_ID int NOT NULL COMMENT '게시글 ID',
	BOARD_CODE varchar(10) NOT NULL,
	TITLE varchar(400),
	CONTENTS text,
	DEL_YN char(1) DEFAULT 'N',
	IN_USER varchar(20) NOT NULL,
	IN_DATE datetime NOT NULL,
	UP_USER varchar(20),
	UP_DATE datetime,
	PRIMARY KEY (BA_ID)
);


CREATE TABLE TB_BOARD_COMMENT
(
	BC_ID int NOT NULL,
	-- 게시글 ID
	BOARD_ID int NOT NULL COMMENT '게시글 ID',
	PARENT_BC_ID int NOT NULL,
	CONTENTS varchar(2000),
	DEL_YN char(1) DEFAULT 'N',
	IN_USER varchar(20) NOT NULL,
	IN_DATE datetime NOT NULL,
	UP_USER varchar(20),
	UP_DATE datetime,
	PRIMARY KEY (BC_ID)
);


CREATE TABLE TB_FILE_INFO
(
	FILE_ID int NOT NULL,
	UPLOAD_GROUP varchar(20),
	UPLOAD_GR_SUB varchar(20),
	-- 파일업로드한 게시판 정보 ID
	UPLOAD_ID varchar(20) COMMENT '파일업로드한 게시판 정보 ID',
	ORG_FILE_NAME varchar(500),
	SYS_FILE_NAME varchar(500),
	FILE_PATH varchar(500),
	FILE_SIZE decimal,
	FILE_EXT varchar(10),
	DEL_YN char(1) DEFAULT 'N',
	IN_USER varchar(20) NOT NULL,
	IN_DATE datetime NOT NULL,
	UP_USER varchar(20),
	UP_DATE datetime,
	PRIMARY KEY (FILE_ID)
);



/* Create Foreign Keys */

ALTER TABLE TB_BOARD_ANSWER
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES TB_BOARD (BOARD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_BOARD_COMMENT
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES TB_BOARD (BOARD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_BOARD_COMMENT
	ADD FOREIGN KEY (PARENT_BC_ID)
	REFERENCES TB_BOARD_COMMENT (BC_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



